# Generated by Django 4.2.20 on 2025-10-06 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='token',
            field=models.CharField(max_length=300, verbose_name='Tokenized Title'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('user', 'token')},
        ),
    ]
