# Generated by Django 4.2.20 on 2025-05-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_utilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='configuration',
            field=models.JSONField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
