# Generated by Django 4.2.20 on 2025-05-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_utilities', '0002_alter_aimodel_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=800, verbose_name='Text of Chunk')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, verbose_name='Path of Store')),
                ('text', models.TextField(max_length=5000, verbose_name='Origin Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='configuration',
            field=models.JSONField(blank=True, null=True, verbose_name='Configuration'),
        ),
    ]
