# Generated by Django 4.2.20 on 2025-05-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_utilities', '0004_vectorstore_document_vectorstore_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model',
            field=models.CharField(choices=[('gpt-4o-mini', 'gpt-4o-mini'), ('gemini-2.0-flash', 'gemini-2.0-flash')], default='', max_length=300, verbose_name='Ai Agent Model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(choices=[('open_ai', 'Open AI'), ('gemini', 'Gemini')], max_length=300, verbose_name='AI Agent Name'),
        ),
    ]
