# Generated by Django 4.2.20 on 2025-05-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courses.section', verbose_name='User'),
            preserve_default=False,
        ),
    ]
