# Generated by Django 4.2.20 on 2025-05-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_message_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courses.section', verbose_name='Section'),
        ),
    ]
