# Generated by Django 4.2.20 on 2025-09-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='courses.section', verbose_name='section')),
            ],
        ),
    ]
