# Generated by Django 4.2.20 on 2025-09-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.message', verbose_name='Related Message'),
        ),
    ]
