# Generated by Django 4.2.20 on 2025-10-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_message_related_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='related_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='courses.message', verbose_name='Related Message'),
        ),
    ]
