# Generated by Django 4.2.20 on 2025-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_token_alter_subject_unique_together'),
        ('courses', '0008_alter_message_related_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='token',
            field=models.CharField(max_length=300, verbose_name='Tokenized Title'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'token')},
        ),
    ]
