# Generated by Django 4.2.20 on 2025-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_token_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='token',
            field=models.CharField(max_length=300, verbose_name='Tokenized Title'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'token')},
        ),
    ]
