# Generated by Django 4.2.20 on 2025-05-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='documents/', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
