# Generated by Django 4.2.20 on 2025-05-14 20:15

from django.db import migrations, models
import my_study_pal.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_path_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=my_study_pal.documents.models.get_file_path),
        ),
    ]
